### ISSUE TITLE
Adicionar gerenciador de dependências

### ISSUE THREAD

**Issue by lucasoishi** [jplukas/desafio-dafiti#18]
Para ter uma ter uma forma mais sofisticada e limpa de instalar e gerenciar dependências, a sugestão é adotar o poetry: https://python-poetry.org/docs/ como gerenciador de dependência do projeto.

**Comment by lucasoishi** [comment]
A utilização e instalação do poetry é bem simples, porém terá a necessidade de fazer uma mudança no dockerfile para instalação de dependências através da ferramenta. Fora isso, o poetry traz uma maneira fácil, limpa e descomplicada de gerenciar dependências de um projeto python

**Comment by jplukas** [comment]
#19
