### ISSUE TITLE
Nova implementação: data de atualização e quantidade de palavras em um post

### ISSUE THREAD

**Issue by tiagoprn** [jplukas/desafio-dafiti#2]
Implementar em uma nova branch as seguintes melhorias:

- Permitir edição do conteúdo de um post, persistindo a data de atualização na tabela, mostrando essa data nos templates substituindo a data de criação por essa data, e ordenando os posts por data de atualização mais recente.

- Mostrar no template para o usuário a quantidade de palavras em um post (tanto na criação quanto após a edição de um post).

Após terminar, submeter o PR para Code Review, juntamente com o link dessa issue para que o reviewer possa ter contexto das mudanças solicitadas.

**Comment by jplukas** [comment]
Ok, estou com algumas dúvidas quanto ao que foi pedido:

> * Permitir edição do conteúdo de um post, persistindo a data de atualização na tabela, mostrando essa data nos templates substituindo a data de criação por essa data, e ordenando os posts por data de atualização mais recente.

Essa edição do conteúdo de um post deve ser possível fora do admin? E deve ser persistida apenas a data da última atualização ou também a data de criação do post?


> * Mostrar no template para o usuário a quantidade de palavras em um post (tanto na criação quanto após a edição de um post).

Onde essa informação deve aparecer? No formulário de criação/edição de um post, ou na página de exibição do post?

**Comment by jplukas** [comment]
Conversei com o Rocky ele me esclareceu sobre as dúvidas acima.
